### PR TITLE
Rename project

### PR DESCRIPTION
**Pull request by akhmedgaziev**
Rename project from elizabeth-cloud to mimesis-cloud. It's necessary
because original library elizabeth was renamed to mimesis.

### CODE REVIEW

**Review by sobolevn — APPROVED** [review]

**Comment by sobolevn** [comment]
Thanks, @alexandergaziev ! Are you interested in maintaining this project?
I guess, right now it can be improved with the awesome feature from `mimesis` as:
- typing information
- cleaner api

If you are interested I will give you an access to this repository. And I am sure that @lk-geimfari would also be glad to help you.

**Comment by lk-geimfari** [comment]
@sobolevn Absolutely!

**Comment by akhmedgaziev** [comment]
@sobolevn Yes, that would be great.

**Comment by sobolevn** [comment]
@alexandergaziev done. I have also renamed the repo and heroku app.

**Pull request merged**
